language: bash
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo apt-get install -qq tmux
before_script:
  - tmux start-server
  - tmux new-session -s travis -d
  - tmux list-sessions
script:
  - bats tests/
